spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/orders/**
        - id: stock-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/stock/**
        - id: email-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/email/**
